id: AAFBBA2A2
title: Fulfilment Offering for Nyangrel Nyima Özer's Treasure Practice of Black Hayagrīva
  with an Iron Sword
type: translation
pechas:
- ID0D07C7D
- IE929C92E
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:52:13.672219
  last_modified_at: 2023-01-04 11:52:13.672232
  collections:
  - Fifth Dzogchen Rinpoche
  - Works of Tibetan Masters
alignment_to_base:
  ID0D07C7D/D3D4: A161
  IE929C92E/F349: A161
